# Generated by Django 4.2.1 on 2023-05-24 12:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('LearnCrew', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='predmeti',
            old_name='bodovi',
            new_name='ects',
        ),
        migrations.RenameField(
            model_name='predmeti',
            old_name='ime',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='predmeti',
            old_name='sem_izvanredni',
            new_name='sem_izv',
        ),
        migrations.RenameField(
            model_name='predmeti',
            old_name='sem_redovni',
            new_name='sem_red',
        ),
    ]
